name: David van Diepen
favicon: null
layout_spectrum: 0.47749144374392927
typography_spectrum: 0.05387018620967865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2907307578716427
  lightness: 0.7993325542192906
  saturation: 0.029899488668888807
  rhythmicContrast: 0.17209871299564838
purpose: []
